# Site settings
title: "Melek Rzazade"
email: "melekrzdd@gmail.com"
description: > 
baseurl: "" 
url: "https://melekrzdd.github.io/#about" 

github_username:

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:name/
